/// Déclare les commandes exposées au frontend et le dossier du code Android.
/// `tauri-plugin` génère à partir de cette liste les fichiers de permissions
/// attendus par Tauri (permissions/autogenerated/).
const COMMANDS: &[&str] = &[
    "permission",
    "demander_permission",
    "scanner",
    "vignette",
    "url_video",
    "lister_corbeille",
    "mettre_corbeille",
    "restaurer",
    "supprimer_definitivement",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .build();
}
